# Generated by Django 4.1.4 on 2022-12-28 06:54

from django.db import migrations, models
import django.db.models.deletion
import metabase.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEngine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', metabase.models.HashedAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('metabase', 'Metabase')], default='metabase', max_length=50)),
                ('base_url', models.URLField()),
                ('integration_api_key', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmbeddedReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', metabase.models.HashedAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('reference_id', models.CharField(help_text='Report ID on the engine, like question id, dashboard id on Metabase', max_length=50)),
                ('reference_type', models.CharField(choices=[('single_report', 'Question/Single Report'), ('dashboard', 'Dashboard')], max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metabase.reportengine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
